### ISSUE TITLE
Force Text to the New Page

### ISSUE THREAD

**Issue by mtangoo** [utelle/wxpdfdoc#15]
I have Multiple wxRichTextCtrl Documents (XML) that I would like to Print in single PDF. 
I want each Document to start in new Page in the PDF. Is there a way to control that? In MPDF, If I remember well, there is html tag for commanding Printer to start document in new page.

Is that possible with this library?
Thanks

**Comment by utelle** [comment]
Using the method to print wxRichTextCtrl documents to PDF as shown in the sample application would create one PDF document per wxRichTextCtrl document, since the Print method of the wxPdfPrinter always creates a separate PDF document. AFAIK, that's the default behaviour of wxPrinter.

The only way to prevent the creation of separate PDF documents per invocation of the Print method would be to switch to wxPdfDocument template mode. However, the PDF templates supported by wxPdfDocument are restricted to a single page. That is, if your wxRichTextCtrl documents describe multiple pages, then you can't use this approach.

Another way would be to create a combined wxRichTextCtrl document from the wxRichTextCtrl documents you want to print and to insert a page break before each new document. However, I don't know whether it is easily possible to concatenate wxRichTextBuffers. (If you have the XML representation of the documents at hand, you merge the XML documents to a single one on your own.)

Finally, you could create a PDF document per wxRichTextCtrl document and combine them to a single PDF afterwards. wxPdfDocument supports this approach based on external templates (see templates sample coming with wxPdfDocument). This is certainly not the most elegant and efficient way to do it, but it would definitely work.

**Comment by mtangoo** [comment]
>Another way would be to create a combined wxRichTextCtrl document from the wxRichTextCtrl documents you want to print and to insert a page break before each new document. However, I don't know whether it is easily possible to concatenate wxRichTextBuffers. (If you have the XML representation of the documents at hand, you could merge the XML documents to a single one on your own.)

I think this can be easier than the other approaches as I have mostly being able to concatenate buffers (though there are issues am battling still).

I think the problem I have currently is how to insert page break before each Document. Although it is not wxPDFDoc question, can you steer me into the right direction? I mean how to add page break to wxRTC buffer?

>Finally, you could create a PDF document per wxRichTextCtrl document and combine them to a single PDF afterwards. wxPdfDocument supports this approach based on external templates (see templates sample coming with wxPdfDocument). This is certainly not the most elegant and efficient way to do it, but it would definitely work.

This is another way that could be easier. I have to explore it too.

I thank you for detailed post and please excuse my ignorance. Its the first time I use this library.
Cheers!

**Comment by utelle** [comment]
> > [...] concatenate wxRichTextBuffers [...] merge the XML documents to a single one [...]
>
> I think this can be easier than the other approaches as I have mostly being able to concatenate buffers (though there are issues am battling still).
>
> I think the problem I have currently is how to insert page break before each Document. Although it is not wxPDFDoc question, can you steer me into the right direction? I mean how to add page break to wxRTC buffer?

I don't have much experience in using `wxRichTextCtrl`. However, you will have to apply `wxRichTextAttr::SetPageBreak` somehow, before appending the buffer of the next wxRichTextCtrl document.

> > Finally, you could create a PDF document per wxRichTextCtrl document and combine them to a single PDF afterwards. wxPdfDocument supports this approach based on external templates (see templates sample coming with wxPdfDocument). This is certainly not the most elegant and efficient way to do it, but it would definitely work.
>
> This is another way that could be easier. I have to explore it too.

From the standpoint of implementation it is quite simple. For each generated PDF document, you would have to execute the following sequence of statements:
```
wxPdfDocument pdfDoc;
// ...
int pageCount = pdfDoc.SetSourceFile("pdf file name");
for (int p = 1; p <= pageCount; ++p)
{
  pdfDoc.AddPage();
  int tpl = pdfDoc.ImportPage(p);
  pdfDoc.UseTemplate(tpl)
} 
```
It might be necessary to adjust the template position and extent (optional parameters of method UseTemplate).

> I thank you for detailed post and please excuse my ignorance. Its the first time I use this library.

You are welcome.

**Comment by mtangoo** [comment]
let me test both way and see which is the easiest

**Comment by mtangoo** [comment]
let me test both way and see which is the easiest

**Comment by mtangoo** [comment]
In case anyone meets same problem here is what I used:

```cpp
wxRichTextBuffer *cummulative = new wxRichTextBuffer();
//...... some code here
wxRichTextAttr pageBreakStyle;
pageBreakStyle.SetPageBreak();
cummulative->BeginStyle(pageBreakStyle);
cummulative->BeginBold();
cummulative->AddParagraph(title); 
cummulative->EndBold(); 
cummulative->EndStyle();
```

I will test the other option but so far I have my problem solved!
