### ISSUE TITLE
wxPENSTYLE_DOT does not have dots

### ISSUE THREAD

**Issue by mael15** [utelle/wxpdfdoc#32]
wxPENSTYLE_DOT looks more like dashes, although not exactly the same as wxPENSTYLE_LONG_DASH or wxPENSTYLE_SHORT_DASH. i see dots in my app using wxMemoryDC, but not in the same code using wxPdfDC.

i am using 0.9.6.

**Comment by utelle** [comment]
Probably this is a bug in setting up the line style associated with the pen for PDF output in method `SetupPen`. While the pen width is scaled, the dash pattern is not. For real dashes this probably is not so important, but for a dotted line it will be necessary to scale the dash pattern according to the line width, so that the resulting line doesn't look dashed, but dotted.

This should not be too difficult to fix. Maybe just taking the scaled line width instead of the fixed number 1 solves the problem.

**Comment by utelle** [comment]
I adjusted the pattern specifications for the various pen styles. I hope the new specifications meet better the expectations. Please give it a try.

**Comment by mael15** [comment]
thank you for the super fast answer! i am not sure if the situation changed, maybe it got better, but not perfect yet. this is how it looks now, pdf on the bottom: https://drive.google.com/file/d/0B3ufm_rZo3qJcTVIMVNpSjJ1RVU/view?usp=sharing

**Comment by utelle** [comment]
The problem has to do with the pen cap style. In the default case (wxCAP_ROUND) a half circle is added on both sides of a line. So, for a perfect circle line length of the dash pattern has to be 0.

I adjusted the code to take the pen cap style into account. Please give it another try.

**Comment by mael15** [comment]
yes, now it is perfect, thank you very much!

**Comment by utelle** [comment]
Thanks for confirming.
