### ISSUE TITLE
Method 'RegisterFont' for wxFont instances is not available for platform WXMAC.

### ISSUE THREAD

**Issue by mtangoo** [utelle/wxpdfdoc#44]
Hi,
Thanks for useful library. I was exporting PDF from wxRichTextCtrl and I found that error. The sample log is presented below. After hitting continue in Error dialog, PDF is generated but the size is the same (as bold as the heading is). I guess am doing something wrong that uses methods that i unavailable but cannot figure our. Below is also the sample code.

**The Log**
>17:27:12: wxPdfFontManagerBase::RegisterFont: Method 'RegisterFont' for wxFont instances is not available for platform WXMAC.
>17:27:12: wxPdfFontManagerBase::RegisterFont: Method 'RegisterFont' for wxFont instances is not available for platform WXMAC.

Sample code

```cpp
void Notes::OnExportPDF(wxCommandEvent& event)
{
    wxPageSetupDialogData dialogData = wxPageSetupDialogData();
    dialogData.SetMarginTopLeft(wxPoint(25,25));
    dialogData.SetMarginBottomRight(wxPoint(25,25));
    dialogData.EnableMargins(true);
    dialogData.EnablePaper(true);
    dialogData.EnableOrientation(true);

    wxPdfPageSetupDialog* dialog = new wxPdfPageSetupDialog(wxTheApp->GetTopWindow(), &dialogData);
    if(dialog->ShowModal() == wxID_OK)
    {
        dialogData = dialog->GetPageSetupData();
        wxPdfPrintData printData = wxPdfPrintData(&dialogData);
        //user info
        printData.SetDocumentAuthor(wxGetUserName());
        printData.SetFilename("Sample.pdf");

        wxPdfPrintDialog *printDialog =  new wxPdfPrintDialog(wxTheApp->GetTopWindow(), &printData);
        if(printDialog->ShowModal() == wxID_OK)
        {
            printData = printDialog->GetPdfPrintData();
            m_printer->SetRichTextBufferPrinting(new wxRichTextBuffer());

            wxRichTextPrintout *printPrintout = new wxRichTextPrintout(wxT("Export to PDF"));
            // richtext printout accepts margins in tenths of mm
            printPrintout->SetMargins(
                10 * dialogData.GetMarginTopLeft().y,
                10 * dialogData.GetMarginBottomRight().y,
                10 * dialogData.GetMarginTopLeft().x,
                10 * dialogData.GetMarginBottomRight().x
            );

            wxRichTextBuffer *printBuffer = GetNoteBuffer();
            printPrintout->SetRichTextBuffer(printBuffer);

            wxPdfPrinter *printer = new wxPdfPrinter(&printData);
            // don't show a print dialog again - we have already done so
            printer->Print(this, printPrintout, false);
            //delete printBuffer;
            delete printer;
            delete printPrintout;

        }
        delete printDialog;
    }
    delete dialog;
}
```

**Comment by utelle** [comment]
Font support for WXMAC was implemented more than 7 years ago. Back then I asked a friend to test the implementation, because I don't have access to a Mac OS X computer myself. The latter hasn't changed.

The problem is that obviously the symbols `wxOSX_USE_CORE_TEXT` (and  `wxOSX_USE_ATSU_TEXT`) are no longer defined in **_wxWidgets 3.x_** (as they were in wxWidgets up to version 2.9). Maybe this means that using "core text" is now the default, but I really don't know, since I have no OSX experience at all.

You could try the following:

Modify file `pdffontmacosx.h` in the `include/wx` folder of the **_wxPdfDocument_** distribution by changing **_line 20_** from

```
#if wxCHECK_VERSION(2,9,0)
```
to
```
#if wxCHECK_VERSION(3,0,0)
  // wxWidgets 3.0.0 or higher
  #define wxPDFMACOSX_HAS_CORE_TEXT 1
  #define wxPDFMACOSX_HAS_ATSU_TEXT 0
#elif wxCHECK_VERSION(2,9,0)
```
If we are lucky, this will work. 

Please let me know the results, when you have tested this modification. If it works, I will gladly apply the above patch to **_wxPdfDocument_**.

Regards,

Ulrich

**Comment by vadz** [comment]
These symbols are indeed not defined any more in wx 3.1, which always uses CoreText AFAIK. So the fix above should be correct, but `wxCHECK_VERSION(3,1,1)` should be used as ATSU support was dropped in wxWidgets/wxWidgets@c9b1ebf8168b5cfe6e1e001447d62d0762538ba0

**Comment by utelle** [comment]
IMHO using `wxCHECK_VERSION(3,0,0)` is the right thing to do, since wxWidgets version 3.0.x is still around (with version 3.0.4 being the latest _stable release_). 

Version 3.0.x doesn't define `wxOSX_USE_CORE_TEXT`, but it **does** define `wxOSX_USE_ATSU_TEXT`. If `wxOSX_USE_ATSU_TEXT == 1` this would force wxPdfDocument to use ATSU (which seems to be deprecated), while CoreText would be the better option, but would make wxPdfDocument fail if `wxOSX_USE_ATSU_TEXT == 0`, even though CoreText is available.

wxPdfDocument uses CoreText, if it is available, and resorts to ATSU only, if CoreText is not available. I don't know whether this was the best approach due to lack of OSX experience, but over the last 7 years no one complained.

**Comment by mtangoo** [comment]
Thanks guys for the comments. Let me make changes and if it works I will send a PR
Cheers!

**Comment by vadz** [comment]
Just to be clear: 3.0 can still use ATSU (if `wxOSX_USE_ATSU_TEXT` is defined as 1) or CoreText (if `wxOSX_USE_ATSU_TEXT` is defined as 0), while 3.1 and later always use CoreText.

**Comment by utelle** [comment]
Maybe we then have to introduce yet another case for wxWidgets **_3.0.x_**, namely checking for `wxOSX_USE_ATSU_TEXT` and using ATSU, if the symbol is set to 1, and using CoreText, if the symbol is set to 0.

However, I'm not convinced that this is really the best solution. In fact, wxPdfDocument uses method `OSXGetCTFont` of `wxFont` to get a `CTFontRef` of the font. As far as I can see, method `OSXGetCTFont` is always available in wxWidgets **_3.0.x_**, independent of the value of `wxOSX_USE_ATSU_TEXT`. This was not the case for prior versions of wxWidgets.

I don't know whether there is a difference between a CoreText and ATSU font, which makes them incompatible to each other somehow. For wxPdfDocument only counts that it can access the real font data. This is possible through a `CTFontRef`. If this type of font reference is always accessible in wxWidgets **_3.0.x_**, I would prefer that method.

If ATSU is used, wxPdfDocument uses the method `MacGetATSUFontID` of `wxFont`, which is flagged as deprecated. This ID is then used by wxPdfDocument to detect the name of the associated font file.

**Comment by utelle** [comment]
Since wxWidgets 3.x always supports CoreText under wxMAC, the adjustment proposed earlier was now applied, because I'm confident that this modification fixes the problem with method `RegisterFont` for `wxFont` objects.

Feel free to reopen the issue, if the problem persists.

**Comment by utelle** [comment]
It was necessary to add the following `#include` in case of wxWidgets 3.x:
```
  #include <wx/osx/private.h>
```
Now wxPdfDocment compiles without errors, and I'm confident that it will work at runtime, too.

**Comment by mtangoo** [comment]
Thank you. Sorry these few weeks I have been well occupied and could not test as I promised.
I will test it this week and feedback

**Comment by utelle** [comment]
No problem. As said I'm rather confident that the modification I applied solves the problem. However, you should download the latest sources, because the fix I mentioned in a previous post is not enough - the statement `#include <wx/osx/private.h>` has to be added.

Reopen the issue, if it doesn't work.

**Comment by mtangoo** [comment]
I just tested, and I can confirm the problem is gone and the PDF is nice one.
Thanks for the library. Time to dig deeper!
