### ISSUE TITLE
How to print and print preview existing PDF files ?

### ISSUE THREAD

**Issue by nowgoing** [utelle/wxpdfdoc#58]

**Comment by utelle** [comment]
**wxPdfDocument** is a component for generating PDF documents. It is **not** a component for parsing, displaying or printing PDF documents.

Your options for printing or previewing a PDF document vary depending on your approach for generating the PDF document.

If you generate a PDF document using **wxPdfDocument**, the easiest way to display/preview and print it is to invoke the default PDF viewer application of the system using the below (or similar) code. This is the approach I typically use for my own applications.

```C++
#include <wx/mimetype.h>

wxString pdfFileName = "...";
wxFileType* fileType = wxTheMimeTypesManager->GetFileTypeFromExtension(wxT("pdf"));
if (fileType != NULL)
{
  wxString cmd = fileType->GetOpenCommand(pdfFileName);
  if (!cmd.IsEmpty())
  {
    long rc = wxExecute(cmd);
    // you may want to handle the case rc != 0
  }
  delete fileType;
}
```

If you generate a PDF document using the **wxWidgets** printing framework based on the class **wxPdfDC**, you may use the methods provided by the printing framework (see the [**pdfdc** sample application](https://github.com/utelle/wxpdfdoc/tree/master/samples/pdfdc) coming with **wxPdfDocument**). However, **wxPdfDC** doesn't (**and can't**) make all features of **wxPdfDocument** accessible.

Finally, you would have the option to integrate a PDF viewer component like [wxPDFView](https://github.com/TcT2k/wxPDFView), which is based on [PDFium](https://pdfium.googlesource.com/pdfium/), into your application. However, as far as I know it is not trivial to get **wxPDFView** up and running.

**Comment by nowgoing** [comment]
Thank you very much for your answer.As you said I tried to compile **wxPDFView** very complicated. **wxpdfdoc** is easy to use, so why not add an interface to drive your printer to print existing PDF files?Can make **wxpdfdoc** more powerful.

**Comment by utelle** [comment]
Although some printers exist that are capable of printing PDF files directly, most printers do not offer this feature. Therefore printing a PDF file usually involves a PDF renderer (like Adobe Acrobat Reader, PDFium etc), which then in turn interacts with a printer via a device driver.

Currently I do not intend to add renderer capabilities to **wxPdfDocument**, because this would be kind of reinventing the wheel. Implementing a PDF renderer on a similar level as Adobe Acrobat Reader would really be a major task.

All major OSes provide a PDF viewer, which could be used to display (and to trigger printing of) a PDF file using the code shown in my first answer. So at least I could imagine to add a convenience function to **wxPdfDocument** for invoking the system PDF viewer.

Up to now the users of my own applications were quite happy with using the system PDF viewer for preview and printing. From the user's perspective this is a good approach in most use cases, because in general all users know how to operate the system PDF viewer. No need to learn to operate yet another tool.

If fine-grained control over the preview or printing process is necessary for some reason, one would have to go through the pain to add for example **wxPDFView** to the application, or to implement some sort of remote control for the system PDF viewer, unfortunately. However, the latter usually can't be implemented in a platform independent way easily.

Sorry, that I don't have a better answer for you.

**Comment by nowgoing** [comment]
Thanks again for your careful answer！
