### ISSUE TITLE
NOOB ALERT - The compiled dll is giving me segmentation error in GetFont Function in pdffontmanager.cpp @ 1753

### ISSUE THREAD

**Issue by JNaik14** [utelle/wxpdfdoc#79]
**My PC:**
Windows 7 x64
G630 8GB GT710

Code Blocks 20.03
wxPDFDocument 1.0.1
wxWidgets 3.1.5

**Code:**

GDB says the return statement of the 'Get Font' function at [1753 ](https://github.com/utelle/wxpdfdoc/blob/5bdcdb9953327d06dc50ec312685ccd9bc8400e0/src/pdffontmanager.cpp#L1753)@ pdffontmanager.cpp is causing the segmentation fault.

I ran a earlier code base by using the 0.9.8 version of the library. Were there any changes related to Fonts in anyway.

![Call stack given by codeblocks (gdb)](https://user-images.githubusercontent.com/52251534/134709622-5fb3b412-d0d1-4112-9f78-8d0e38cda21f.PNG)

**Comment by utelle** [comment]
> GDB says the return statement of the 'Get Font' function at [1753 ](https://github.com/utelle/wxpdfdoc/blob/5bdcdb9953327d06dc50ec312685ccd9bc8400e0/src/pdffontmanager.cpp#L1753)@ pdffontmanager.cpp is causing the segmentation fault.

In fact, I can't see any reason why and how the return statement in the `GetFont` method could cause a segmentation fault. Even if the font that should be loaded had not been found, the method would return an uninitialized `wxPdfFont` instance.

Quite often segmentation faults are caused by errors that occurred earlier at some other place in the application, for example, if the application writes to an array out of bounds.

> I ran a earlier code base by using the 0.9.8 version of the library. Were there any changes related to Fonts in anyway.

No, there were no relevant changes to the `wxPdfFontManager` class after the release of version 0.9.8.

**Comment by JNaik14** [comment]
Thanks for the quick response. I'll look into it.

**Comment by utelle** [comment]
I have to admit that your error description misled me. Looking closer at the debugger screenshot I see that the `this` pointer is null. That indicates that the global font manager was not initialized, which is usually instantiated automatically through the wxModule mechanism of wxWidgets. This can only happen, if wxWidgets itself was not properly initialized.

**Comment by JNaik14** [comment]
I compiled the widgets library as monolithic and static, I think the static code cannot communicate with the wxpdf DLL.
wxpdf works with static code,right?

**Comment by utelle** [comment]
In principle, wxPdfDocument can be used together with a static wxWidgets library. However, in that case wxPdfDocument should be compiled as a static library, too. Otherwise your application uses 2 instances of the wxWidgets library, one from the main application and one from the wxPdfDocument DLL. The one in the DLL will not get initialized, explaining the problem you experience.

If you want to use wxPdfDocument as a DLL, you have to use a wxWidgets DLL as well. Otherwise you are asking for trouble.

This is not a wxPdfDocument specific problem, but is true in general.

**Comment by JNaik14** [comment]
It Worked.
I recompiled wxWidgets as a shared library and then wxPdfDocument.
Thank you very much for the help.
Just troubling you for a last time. 
How can i compile the library in static mode?

**Comment by utelle** [comment]
The easiest approach to generate a static wxPdfDocumentlibrary will be to use the `Makefile` coming with wxPdfDocument. This file is located in the `build` directory of the wxPdfDocument distribution. You just invoke your make tool with the appropriate configuration. Example:
```
mingw32-make config=release_win32
```
for a static library 32-bit in release mode. Replace _release_ by _debug_ for debug mode. Replace _win32_ by _win64_ for a 64-bit version. 

You will have to adjust the file `config.gcc` to match your wxWidgets installation.

**Comment by JNaik14** [comment]
Thank You very much for the help.
I was finally able to cram everything into a single exe.
