### ISSUE TITLE
Invalid pdf-document generated

### ISSUE THREAD

**Issue by sveinl** [utelle/wxpdfdoc#86]
I have been struggling with this for past 3 days now trying different things - but gave up eventually.
I am on Windows 11, MSVC 2022, wxWidgets 3.2.1, wxPdfDocument 1.0.2 - all compiled with unicode - statically linked.

The code used to generate the pdf is this: 
```wxPdfDocument pdf;
pdf.SetCompression(false);
pdf.AddPage();
pdf.SetFont(wxS("Helvetica"), wxS(""), 14);
pdf.Cell(10, 10, wxS("This is some text"));
wxString path = "test.pdf";
pdf.SaveAsFile(path);
```

Result is a blank PDF (when opened with chrome - Adobe reader wont open it but gives error 110).
PDF attached. I dont know PDF-language too well so i hope to get som input to get this solved.
I also posted in the [wxCode forum](https://forums.wxwidgets.org/viewtopic.php?f=30&t=50159)

[test.zip](https://github.com/utelle/wxpdfdoc/files/10796729/test.zip)

**Comment by sveinl** [comment]
> ```c++
> wxString numUsingCurrentLocale = wxString::FromDouble(3.1415, 2);
> wxString numUsingCLocale = wxString::FromCDouble(3.1415, 2);
> ```
Both gives 3,14 with comma.

**Comment by sveinl** [comment]
> ```
> std::locale::global(std::locale("norwegian"));
> ```
I removed this line and everything works fine.

**Comment by sveinl** [comment]
> > I have been struggling with this for past 3 days now trying different things - but gave up eventually.
> 
> I'm sorry to hear that.

Oh, no worries... i didnt mean blame you at all... was just an excuse for me to bother you with my problem :)

**Comment by sveinl** [comment]
> > ```
> > std::locale::global(std::locale("norwegian"));
> > ```
> 
> I removed this line and everything works fine.

I am using a work-around for now. Before using wxPdfDocument i do 
```std::locale::global(std::locale("english"));``` and just after i reset it to norwegian with ```std::locale::global(std::locale("norwegian"));```

Thank you for taking the time to look into this!

**Comment by sveinl** [comment]
> Does your application change the locale (using one of the classes `wxLocale` or `wxUILocale`)? If so, which locale? What is the locale of your Windows system?

Yes, i did change the locale with ```std::locale::global(std::locale("norwegian"));```

> Please add the following lines and inspect the resulting strings
> 
> ```c++
> wxString numUsingCurrentLocale = wxString::FromDouble(3.1415, 2);
> wxString numUsingCLocale = wxString::FromCDouble(3.1415, 2);
> ```
> 
> For `numUsingCurrentLocale ` the expected result is: **3,14** (separator: comma). For `numUsingCLocale ` the expected result is: **3.14** (separator: point).

They both return 3,14 with comma.

> If `wxString::FromCDouble()` does not return a string with a point as decimal separator for you, then there is a bug either in wxWidgets or in the code generated by MSVC 2022.
It doesnt return string with point, but comma.

I am now changing the local only for the collating ```std::setlocale(LC_COLLATE, "nb_NO.UTF-8");```
Now the pdf is created fine and sorting also works as expected.

```wxString::FromCDouble(3.1415, 2);``` is still returning comma as decimal-separator when i change the locale with LC_ALL like this ```std::setlocale(LC_ALL, "nb_NO.UTF-8");``` - i dont know if thats a bug or feature.

**Comment by utelle** [comment]
> Yes, i tried using
> ```
> std::locale::global(std::locale("norwegian"));
> ```
> to get norwegian chars to be sorted correctly using std::sort. Could that be the reason?

Yes, I'm pretty sure that that explains the problem.

Since you use wxPdfDocument in your application I assume(d) that your whole application is based on wxWidgets. Is that correct?

For a wxWidgets based application you should use the static method [wxUILocale::UseDefault()](https://docs.wxwidgets.org/3.2.1/classwx_u_i_locale.html#a86af3ae9d8558b59464028206170a856) to configure the application to use the default locale of the system.

> > ```c++
> > wxString numUsingCurrentLocale = wxString::FromDouble(3.1415, 2);
> > wxString numUsingCLocale = wxString::FromCDouble(3.1415, 2);
> > ```
> 
> Both gives 3,14 with comma.

That is what I suspected. Since you used `std::locale::global(std::locale("norwegian"));` to set the locale (and not the class `wxUILocale`), the wxWidgets library, namely the class `wxUILocale`, does not know that the locale was changed. Therefore the class `wxUILocale` assumes that the C locale is still the current locale and returns a point as the decimal separator. In method `wxString::FromCDouble()` the floating point number is formatted based on the current locale (here using a comma), but the class `wxUILocale` returns the separator of the C locale (here a point) which is used to replace the separator in the formatted number by a decimal point. This doesn't work because the method searches for a point (to replace it by a point), but the actual separator is a comma and is not found (and therefore not replaced).

> > ```
> > std::locale::global(std::locale("norwegian"));
> > ```
> 
> I removed this line and everything works fine.

No surprise.

> I am using a work-around for now. Before using wxPdfDocument i do `std::locale::global(std::locale("english"));` and just after i reset it to norwegian with `std::locale::global(std::locale("norwegian"));`

If you use `wxUILocale` to set the locale, this work-around should no longer be necessary.

**Comment by sveinl** [comment]
> Since you use wxPdfDocument in your application I assume(d) that your whole application is based on wxWidgets. Is that correct?

That is correct yes.

> For a wxWidgets based application you should use the static method [wxUILocale::UseDefault()](https://docs.wxwidgets.org/3.2.1/classwx_u_i_locale.html#a86af3ae9d8558b59464028206170a856) to configure the application to use the default locale of the system.

I did that now and everything works as expected.

I was looking at the wxUILocale but didnt understand how it was meant to be used. 

Thank you for helping me out and for this great pdf-library!

**Comment by utelle** [comment]
> > For a wxWidgets based application you should use the static method [wxUILocale::UseDefault()](https://docs.wxwidgets.org/3.2.1/classwx_u_i_locale.html#a86af3ae9d8558b59464028206170a856) to configure the application to use the default locale of the system.
> 
> I did that now and everything works as expected.

Good to hear that. Nevertheless I opened an issue https://github.com/wxWidgets/wxWidgets/issues/23287 in the wxWidgets project, because IMHO `wxString::FromCDouble()` should not fail unexpectedly, if the locale was modified via C++ STL (even if that could be called a misuse in a wxWidgets application).

> Thank you for helping me out and for this great pdf-library!

You are welcome.

**Comment by sveinl** [comment]
Maybe not the right place to ask this question - and i can delete it afterwards if you want.
Is there a way to keep whole paragraph on the same page? I mean if there will be a pagebreak in the middle of a paragraph, then the whole paragraph is moved to the next page.

As far as i can see the milticell just output muliple cells and then only the actual cell is moved to a new page in case of a pagebreak.

**Comment by utelle** [comment]
> Maybe not the right place to ask this question - and i can delete it afterwards if you want.

Well, your question is not related to the topic of this issue. Therefore next time it would be better to open another issue or a discussion (depending on the type of question).

> Is there a way to keep whole paragraph on the same page? I mean if there will be a pagebreak in the middle of a paragraph, then the whole paragraph is moved to the next page.

wxPdfDocument is not a full-blown text-layout engine. Therefore its layout options are limited. However, you could achieve the goal by using the markup supported by wxPdfDocument: you can put the paragraph in a table cell, and the algoritm will try to keep the cell resp the row containing the cell on the same page.

> As far as i can see the multicell just output muliple cells and then only the actual cell is moved to a new page in case of a pagebreak.

That is correct. Method `wxPdfDocument::MultiCell()` will perform page breaks whenever the bottom of a page is reached.
