### ISSUE TITLE
Additional page break when table doesn't fit on page and has only one row

### ISSUE THREAD

**Issue by stkruse** [utelle/wxpdfdoc#91]
There's one more edge case where the current implementation doesn't work as expected: In case that there's just on table row, which doesn't fit on the current page. In this case an empty page is inserted and the table on the page behind.

I've two implementations to fix this issue:

The first is a slightly adjusted implementation of the current code: stkruse/wxpdfdoc@679133885618fc4b8853844cf90c63391f48d103

The second one introduces a helper struct which makes it easier to understand what happens stkruse/wxpdfdoc@af0bfcc6a12b8960846c3119e285adf595759f03
Personally, I think the second implementation is better.
But, it uses one C++11 feature, the ```using``` directive. But in case you want to support compiler which haven't implemented the C++11 standard, it could be replaced with a ```typedef```.

**Comment by utelle** [comment]
> There's one more edge case where the current implementation doesn't work as expected: In case that there's just on table row, which doesn't fit on the current page. In this case an empty page is inserted and the table on the page behind.
> 
> I've two implementations to fix this issue:
> 
> The first is a slightly adjusted implementation of the current code: [stkruse/wxpdfdoc@6791338](https://github.com/stkruse/wxpdfdoc/commit/679133885618fc4b8853844cf90c63391f48d103)
> 
> The second one introduces a helper struct which makes it easier to understand what happens [stkruse/wxpdfdoc@af0bfcc](https://github.com/stkruse/wxpdfdoc/commit/af0bfcc6a12b8960846c3119e285adf595759f03) Personally, I think the second implementation is better.

I made a few experiments using the markup example coming with wxPdfDocument. I tried both implementations. Results differ, but both do not actually solve the problem, unfortunately. See details below.

> But, it uses one C++11 feature, the `using` directive. But in case you want to support compiler which haven't implemented the C++11 standard, it could be replaced with a `typedef`.

Although I'm not against moving to C++11 in principle, wxWidgets itself is still usable with pre-C++11 compilers - at least up to version 3.2.x. AFAIK version 3.3 will require a C++11 compiler. Therefore I would prefer for now a solution which doesn't require C++11 to not break existing applications which have to use an older compiler for whatever reason..

Once wxWidgets 3.3 will be released officially, a new version of wxPdfDocument that also requires C++11 could be released. (Actually, I plan an even more radical step for a future version of wxPdfDocument, namely requiring C++20.)

Back to the markup table problem.

I modified the markup example by changing the first row of the table in variable `xmlString6`

1) First row higher than fits on the current page

```c++
wxString(wxS("<tr><td>This<br />is<br />a<br />table<br />cell<br />with<br />some<br />text.<br />This<br />is<br />a<br />table<br />cell<br />with<br />some<br />text.<br />This<br />is<br />a<br />table<br />cell<br />with<br />some<br />text.<br /></td></tr>")) +
```
Variant 1: [xmlwrite-v1a.pdf](https://github.com/utelle/wxpdfdoc/files/13431649/xmlwrite-v1a.pdf)
Variant 2: [xmlwrite-v1b.pdf](https://github.com/utelle/wxpdfdoc/files/13431654/xmlwrite-v1b.pdf)

Several pages with partial table rows.

2) First row higher than in test case (1), but still fitting on a page

```c++
wxString(wxS("<tr><td>This<br />is<br />a<br />table<br />cell<br />with<br />some<br />text.<br />This<br />is<br />a<br />table<br />cell<br />with<br />some<br />text.<br />This<br />is<br />a<br />table<br />cell<br />with<br />some<br />text.<br />This<br />is<br />a<br />table<br />cell<br />with<br />some<br />text.<br />This<br />is<br />a<br />table<br />cell<br />with<br />some<br />text.<br />This<br />is<br />a<br />table<br />cell<br />with<br />some<br />text.<br />This<br />is<br />a<br />table<br />cell<br />with<br />some<br />text.<br /></td></tr>")) +
```
Variant 1: [xmlwrite-v2a.pdf](https://github.com/utelle/wxpdfdoc/files/13431717/xmlwrite-v2a.pdf)
Variant 2: [xmlwrite-v2b.pdf](https://github.com/utelle/wxpdfdoc/files/13431719/xmlwrite-v2b.pdf)

Several pages with partial table rows.

3) First row even higher than in test case (2), no longer fitting on a page

```c++
wxString(wxS("<tr><td>This<br />is<br />a<br />table<br />cell<br />with<br />some<br />text.<br />This<br />is<br />a<br />table<br />cell<br />with<br />some<br />text.<br />This<br />is<br />a<br />table<br />cell<br />with<br />some<br />text.<br />This<br />is<br />a<br />table<br />cell<br />with<br />some<br />text.<br />This<br />is<br />a<br />table<br />cell<br />with<br />some<br />text.<br />This<br />is<br />a<br />table<br />cell<br />with<br />some<br />text.<br />This<br />is<br />a<br />table<br />cell<br />with<br />some<br />text.<br />This<br />is<br />a<br />table<br />cell<br />with<br />some<br />text.<br /></td></tr>")) +
```
Variant 1 and 2: [xmlwrite-v3.pdf](https://github.com/utelle/wxpdfdoc/files/13431745/xmlwrite-v3.pdf)

As can be seen the table is not written to the PDF file at all. Yes, one gets an error message - as we discussed last time. However, it might be better to output the table nevertheless, because this allows a developer to analyze the problem in more detail.

It would be great, if you could try to find a solution. TIA.

**Comment by stkruse** [comment]
I switched from ```using``` to ```typedef``` so it should work fine with pre c++11 compilers.
Additional I overworked the error handling (stkruse/wxpdfdoc@7f7e0d80cd70b283e96f3e5e0fa3315ce2e72f3b)
- I try to print the table even if a line doesn't fit on an empty page 
- I check every line since not only the first line could be to big

**Comment by utelle** [comment]
I partially applied your first implementation and made a few further adjustments. AFAICT this variant produces the same results as your second implementation, but incurs less changes to the code base. Could you please check whether this implementation handles your use cases correctly. If not, please provide a sample exhibiting the remaining problems.

**Comment by utelle** [comment]
> I switched from `using` to `typedef` so it should work fine with pre c++11 compilers. Additional I overworked the error handling ([stkruse/wxpdfdoc@7f7e0d8](https://github.com/stkruse/wxpdfdoc/commit/7f7e0d80cd70b283e96f3e5e0fa3315ce2e72f3b))
> 
> * I try to print the table even if a line doesn't fit on an empty page
> * I check every line since not only the first line could be to big

You are absolutely right. Theoretically, even the table header rows could be too high. I haven't checked yet what happens if that is the case.

We may consider to handle too high rows differently. Currently the automatic page break lets the row overflow to the next page. As an alternative we could try to avoid this overflow.

> Edit: And, of course I fixed my problem of the first commit, where I forgot to take the first line height into account when we have a line break at the beginning

Yes, the calculation of available and used heights was somewhat flawed.

I hope you are not annoyed that I created a separate implementation based on your first one. I'm really grateful that you brought this table problem to my attention.

**Comment by stkruse** [comment]
I made a few tests and it looks good.

Just in the error case (your third test case) we have now a page with just the table header, one page where it tries to print the table and some overflow on the following page.

But, since we print an error message , now with row of the error included, I think it's pretty clear where the user has to debug his code.

Thanks for fixing this issue.

**Comment by utelle** [comment]
> I made a few tests and it looks good.

Thanks for your feedback.

> Just in the error case (your third test case) we have now a page with just the table header, one page where it tries to print the table and some overflow on the following page.

I will look into that test case once again, but ...

> But, since we print an error message , now with row of the error included, I think it's pretty clear where the user has to debug his code.

... as you pointed out, it is an error case anyway, which typically needs to be addressed by the developer of an application.

However, in case of dynamic content, such problems may arise unexpectedly.

In issue #88 another user asked for support to split a row across pages. I closed that issue as _not planned_, but for handling table rows with a height greater than available page height it could be useful. On the other hand I would not use such a feature for rows that would fit on a page without splitting. Maybe I give it a thought...

> Thanks for fixing this issue.

You are welcome. And thanks again for your efforts.
